=== marianclaudesol/AE_2.XML_DTD_XSD/AE-2.DTD.dtd
<!ELEMENT biblioteca (libros, revistas, periodicos)>
<!-- Definimos los elementos de libros -->
<!ELEMENT libros (libro+)>
<!ELEMENT libro (titulo, indice, sinopsis, capitulos)>

<!-- Definimos los atributos del libro -->
<!ATTLIST libro id ID #REQUIRED>
<!ATTLIST libro pag CDATA #REQUIRED>
<!ATTLIST libro tipo_clase (novela | infantil | didÃ¡ctico) #REQUIRED>

<!-- Definimos los elementos de libro -->
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT indice (#PCDATA)>
<!ELEMENT sinopsis (#PCDATA)>
<!ELEMENT capitulos (capitulo+)>

<!-- Definimos los atributos y elementos de capitulo -->
<!ELEMENT capitulo (titulo, contenido)>

<!-- Definimos los atributos -->
<!ATTLIST capitulo pag CDATA #REQUIRED>


<!-- Definimos los elementos de revistas -->
<!ELEMENT revistas (revista+)>
<!ELEMENT revista (titulo, indice, secciones)>

<!-- Definimos los atributos y los elementos de revista -->
<!ATTLIST revista id ID #REQUIRED>
<!ATTLIST revista tipo_clase (informatica | corazon | coches | investigacion | otras) #REQUIRED>
<!ATTLIST revista fech_pu CDATA #REQUIRED>

<!ELEMENT secciones (seccion+)>
<!ELEMENT seccion (titulo, contenido)>

<!-- Definimos los atributos y elementos de seccion -->
<!ATTLIST seccion pag CDATA #REQUIRED>

<!ELEMENT contenido (#PCDATA)>

<!ELEMENT periodicos (periodico+)>
<!ELEMENT periodico (titulo, indice, secciones_p+)>

<!-- Definimos los atributos de periodico -->
<!ATTLIST periodico id ID #REQUIRED>
<!ATTLIST periodico tipo_clase (nacional | internacional) #REQUIRED>
<!ATTLIST periodico fech_pu CDATA #REQUIRED>


<!-- Definimos los atributos de periodico -->

<!ELEMENT secciones_p (seccion_p+)>

<!-- Definimos los atributos y elemetos de seccion -->
<!ELEMENT seccion_p (articulos+)>
<!ATTLIST seccion_p tipo_sec (economica | opinion | deportes | internacional | nacional) #REQUIRED>

<!ELEMENT articulos (articulo+)>


<!-- Definimos los elemetos de articulo -->
<!ELEMENT articulo (autor, contenido)>
<!ELEMENT autor (#PCDATA)>

=== marianclaudesol/AE_2.XML_DTD_XSD/AE-2. XML,DTD.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE biblioteca SYSTEM "AE-2.DTD.dtd">
<biblioteca>
  <libros>
    <libro id="L0001" pag="276" tipo_clase="infantil">
      <titulo>Las mil y 1 noches</titulo>
        <indice>
         ÍNDICE
         Páginas
         Dedicatoria de la obra
         ................................................................................................................................................................................................................................................................................................................................................................................................
         2
         PRÓLOGO DE E. GÓMEZ CARRILLO
         ................................................................................................................................................................................................................................................................................................................................................................................................
         9
         NOTA DE LOS EDITORES
         ................................................................................................................................................................................................................................................................................................................................................................................................
         17
         UNA PALABRA DEL TRADUCTOR A SUS AMIGOS
         ................................................................................................................................................................................................................................................................................................................................................................................................
         25
         Dedicatoria del primer tomo
         ................................................................................................................................................................................................................................................................................................................................................................................................
         31
         INVOCACIÓN PRELIMINAR
         ¡AQUELLO QUE QUIERA ALAH, EL CLEMENTE, EL MISERICORDIOSO!
         ................................................................................................................................................................................................................................................................................................................................................................................................
         33
         INTRODUCCIÓN
         HISTORIA DEL REY SCHAHRIAR Y DE SU HERMANO EL REY SCHAHZAMAN
         ................................................................................................................................................................................................................................................................................................................................................................................................
         37-51
         en que se explica el origen de los cuentos y se intercala la
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
         FÁBULA DEL ASNO, EL BUEY Y EL LABRADOR
         ................................................................................................................................................................................................................................................................................................................................................................................................
         46-50
         LOS CUENTOS
         HISTORIA DEL MERCADER Y EL EFRIT
         ................................................................................................................................................................................................................................................................................................................................................................................................
         53-70
 	
         Comienza en la primera noche y termina al principiar la 3ª. Se intercalan tres cuentos:
                                                                                                                                                                                                                                                                                                                                                                                                
 	       CUENTO DEL PRIMER JEQUE
         ................................................................................................................................................................................................................................................................................................................................................................................................
         56-62
 	
         CUENTO DEL SEGUNDO JEQUE
         ................................................................................................................................................................................................................................................................................................................................................................................................
         62-67
 	
         CUENTO DEL TERCER JEQUE
         ................................................................................................................................................................................................................................................................................................................................................................................................
         67-69
         HISTORIA DEL PESCADOR Y EL EFRIT
         ................................................................................................................................................................................................................................................................................................................................................................................................
         71-127
 	
         Empieza en la 3ª noche y termina a mediados de la 9.ª — Comprende:
                                                                                                                                                                                                                                                                                                                                                                                                	
         HISTORIA DEL VISIR DEL REY YUNÁN Y DEL MÉDICO RUYÁN
         ................................................................................................................................................................................................................................................................................................................................................................................................
         79-112
 	
         la cual comprende á sn vez:
                                                                                                                                                                                                                                                                                                                                                                                                
         EL HALCÓN DEL REY SINDABAD
         ................................................................................................................................................................................................................................................................................................................................................................................................
         87-39
 	
         HISTORIA DEL PRÍNCIPE Y LA VAMPIRO
         ................................................................................................................................................................................................................................................................................................................................................................................................
         90-92
 	
         y la
