=== marianclaudesol/AE_2.XML_DTD_XSD/Libertad/DTD_Biblioteca.dtd
<!ELEMENT biblioteca (libros, revistas,periodicos)>
    <!ELEMENT libros (libro+)>
    <!ELEMENT libro (titulo, capitulos, indice, sinopsis)>
    <!ELEMENT titulo (#PCDATA)>
    <!ELEMENT capitulos (capitulo+)>
    <!ELEMENT capitulo (titulo, contenido)>
    <!ELEMENT contenido (#PCDATA)>
    <!ELEMENT indice (#PCDATA)>
    <!ELEMENT sinopsis (#PCDATA)>
    
    <!-- Definimos los atributos de libro-->
    <!ATTLIST libro id ID #REQUIRED>
    <!ATTLIST libro tipo_clase (Novela | Infantil | Didactico) #REQUIRED>
    <!ATTLIST libro num_paginas CDATA #REQUIRED>
    <!ATTLIST capitulo num_paginas CDATA #REQUIRED>
    <!ATTLIST contenido enlace_inf CDATA #REQUIRED>

    <!-- Definimos los elementos de revista-->
    <!ELEMENT revistas (revista+)>
    <!ELEMENT revista (titulo, num_revista, indice_contenido, secciones_revista)>
    <!ELEMENT num_revista (#PCDATA)>
    <!ELEMENT indice_contenido (#PCDATA)>
    <!ELEMENT secciones_revista (seccion_rev+)>
    <!ELEMENT seccion_rev (contenido)>
   
    
    <!-- Definimos los atributos de revista-->
    <!ATTLIST revista id ID #REQUIRED>
    <!ATTLIST revista tipo_clase (Informatica | Corazon | Coches | Investigacion | otros) #REQUIRED>
    <!ATTLIST revista num_paginas CDATA #REQUIRED>
    <!ATTLIST seccion_rev num_paginas CDATA #REQUIRED>
    <!ATTLIST contenido enlace_inf CDATA #REQUIRED>

      <!-- Definimos los elementos de periodico-->
    <!ELEMENT periodicos (periodico+)>
    <!ELEMENT periodico (secciones_periodico, indice)>
    <!ELEMENT secciones_periodico (seccion_per)>
    <!ELEMENT seccion_per (articulos)>
    <!ELEMENT articulos (articulo+)>
    <!ELEMENT articulo (contenido)>
   
    
    <!-- Definimos los atributos de revista-->
    <!ATTLIST periodico id ID #REQUIRED>
    <!ATTLIST periodico tipo_clase (Nacional | Internacional) #REQUIRED>
    <!ATTLIST periodico fecha_publi CDATA #REQUIRED>
    <!ATTLIST seccion_per tipo_secciÃ³n (Economica | Deportes | Opinion)  #REQUIRED>
    <!ATTLIST contenido enlace_inf CDATA #REQUIRED>
    <!ATTLIST articulo autor CDATA #REQUIRED>

=== marianclaudesol/AE_2.XML_DTD_XSD/Libertad/DTD_BibliotecaDTDExterna.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE biblioteca SYSTEM "DTD_Biblioteca.dtd">

<biblioteca>
    <libros>
        <libro id="L0001" tipo_clase="Novela" num_paginas="382">
            <titulo>LOS PILARES DE LA TIERRA</titulo>
            <capitulos>
                <capitulo num_paginas="120">
                    <titulo>Capitulo I</titulo>
                    <contenido enlace_inf="http://biblioteca.com/libro1/capitulo1" />
                </capitulo>
                <capitulo num_paginas="140">
                    <titulo>Capitulo II</titulo>
                    <contenido enlace_inf="http://biblioteca.com/libro1/capitulo2" />
                </capitulo>
                <capitulo num_paginas="120">
                    <titulo>Capitulo III</titulo>
                    <contenido enlace_inf="http://biblioteca.com/libro1/capitulo3" />
                </capitulo>
            </capitulos>
            <indice></indice>
            <sinopsis></sinopsis>
        </libro>
        <libro id="L0002" tipo_clase="Infantil" num_paginas="10">
            <titulo>EEL POLLO PEPE</titulo>
            <capitulos>
                <capitulo num_paginas="7">
                    <titulo>Que comió el pollo Pepe para crecer tanto?</titulo>
                    <contenido enlace_inf="http://biblioteca.com/libro2/capitulo1" />
                </capitulo>
                <capitulo num_paginas="1">
                    <titulo>Canción del pollo Pepe</titulo>
                    <contenido enlace_inf="http://biblioteca.com/libro2/capitulo2" />
                </capitulo>
            </capitulos>
            <indice></indice>
            <sinopsis></sinopsis>
        </libro>
        <libro id="L0003" tipo_clase="Didactico" num_paginas="42">
            <titulo>EDUCANDO CON MAGIA</titulo>
            <capitulos>
                <capitulo num_paginas="10">
                    <titulo>I. Llevar La Magia a la Escuela</titulo>
                    <contenido enlace_inf="http://biblioteca.com/libro3/capitulo1" />
                </capitulo>
                <capitulo num_paginas="15">
                    <titulo>II. Juegos de Magia en el Aula</titulo>
                    <contenido enlace_inf="http://biblioteca.com/libro3/capitulo2" />
                </capitulo>
                <capitulo num_paginas="15">
                    <titulo>III. Para saber más sobre Magia</titulo>
                    <contenido enlace_inf="http://biblioteca.com/libro3/capitulo3" />
                </capitulo>
            </capitulos>
            <indice></indice>
            <sinopsis></sinopsis>
        </libro>
    </libros>
    <revistas>
        <revista id="R0001" tipo_clase="Informatica" num_paginas="89">
            <titulo>REVISTA DE TECNOLOGÍA E INFORMÁTICA HISTÓRICA</titulo>
            <num_revista>123</num_revista>
            <indice_contenido></indice_contenido>
            <secciones_revista>
                <seccion_rev num_paginas="22">
                    <contenido enlace_inf="http://biblioteca.com/revista1/seccion1" />
                </seccion_rev>
                <seccion_rev num_paginas="23">
                    <contenido enlace_inf="http://biblioteca.com/revista1/seccion2" />
                </seccion_rev>
                <seccion_rev num_paginas="22">
                    <contenido enlace_inf="http://biblioteca.com/revista1/seccion3" />
                </seccion_rev>
                 <seccion_rev num_paginas="22">
                    <contenido enlace_inf="http://biblioteca.com/revista1/seccion3" />
                </seccion_rev>
            </secciones_revista>
        </revista>
        <revista id="R0002" tipo_clase="Corazon" num_paginas="24">
            <titulo>DIEZ MINUTOS</titulo>
            <num_revista>223</num_revista>
            <indice_contenido></indice_contenido>
            <secciones_revista>
                <seccion_rev num_paginas="8">
                    <contenido enlace_inf="http://biblioteca.com/revista2/seccion1" />
                </seccion_rev>
                <seccion_rev num_paginas="8">
                    <contenido enlace_inf="http://biblioteca.com/revista2/seccion2" />
                </seccion_rev>
                <seccion_rev num_paginas="8">
                    <contenido enlace_inf="http://biblioteca.com/revista2/seccion3" />
                </seccion_rev>
            </secciones_revista>
        </revista>
        <revista id="R0003" tipo_clase="Coches" num_paginas="30">
            <titulo>MOTORLIFE MAGAZINE</titulo>
            <num_revista>323</num_revista>
            <indice_contenido></indice_contenido>
            <secciones_revista>
                <seccion_rev num_paginas="10">
                    <contenido enlace_inf="http://biblioteca.com/revista3/seccion1" />
                </seccion_rev>
                <seccion_rev num_paginas="10">
                    <contenido enlace_inf="http://biblioteca.com/revista3/seccion2" />
                </seccion_rev>
                <seccion_rev num_paginas="10">
                    <contenido enlace_inf="http://biblioteca.com/revista3/seccion3" />
                </seccion_rev>
            </secciones_revista>
        </revista>
        <revista id="R0004" tipo_clase="Investigacion" num_paginas="15">
            <titulo>LOS NUEVOS MUNDOS</titulo>
            <num_revista>423</num_revista>
            <indice_contenido></indice_contenido>
            <secciones_revista>
                <seccion_rev num_paginas="7">
                    <contenido enlace_inf="http://biblioteca.com/revista4/seccion1" />
                </seccion_rev>
                <seccion_rev num_paginas="8">
                    <contenido enlace_inf="http://biblioteca.com/revista4/seccion2" />
                </seccion_rev>
            </secciones_revista>
        </revista>
        <revista id="R0005" tipo_clase="otros" num_paginas="42">
            <titulo>UTILISSIMA</titulo>
            <num_revista>523</num_revista>
            <indice_contenido></indice_contenido>
            <secciones_revista>
                <seccion_rev num_paginas="15">
                    <contenido enlace_inf="http://biblioteca.com/revista5/seccion1" />
                </seccion_rev>
                <seccion_rev num_paginas="12">
                    <contenido enlace_inf="http://biblioteca.com/revista5/seccion2" />
                </seccion_rev>
                <seccion_rev num_paginas="15">
                    <contenido enlace_inf="http://biblioteca.com/revista5/seccion3" />
                </seccion_rev>
            </secciones_revista>
        </revista>
    </revistas>
    <periodicos>
        <periodico id="P0001" tipo_clase="Nacional" fecha_publi="10.05.23">
            <secciones_periodico>
                <seccion_per tipo_sección="Economica">
                    <articulos>
                        <articulo autor="Daniel Lacalle">
                            <contenido enlace_inf="http://biblioteca.com/periodico1/articulo1" />
                        </articulo>
                        <articulo autor="Adam Smith">
                            <contenido enlace_inf="http://biblioteca.com/periodico1/articulo2" />
                        </articulo>
                    </articulos>
                </seccion_per>
            </secciones_periodico>
            <indice></indice>
        </periodico>
         <periodico id="P0002" tipo_clase="Internacional" fecha_publi="01.05.23">
            <secciones_periodico>
                <seccion_per tipo_sección="Deportes">
                    <articulos>
                        <articulo autor="Jose Antonio Abellan">
                            <contenido enlace_inf="http://biblioteca.com/periodico2/articulo1" />
                        </articulo>
                        <articulo autor="Manolo Lama">
                            <contenido enlace_inf="http://biblioteca.com/periodico2/articulo2" />
                        </articulo>
                        <articulo autor="Juanma Castaño">
                            <contenido enlace_inf="http://biblioteca.com/periodico3/articulo3" />
                        </articulo>
                        <articulo autor="Jose Félix Diaz">
                            <contenido enlace_inf="http://biblioteca.com/periodico4/articulo4" />
                        </articulo>
                    </articulos>
                </seccion_per>
            </secciones_periodico>
            <indice></indice>
        </periodico>
         <periodico id="P0003" tipo_clase="Nacional" fecha_publi="12.05.23">
            <secciones_periodico>
                <seccion_per tipo_sección="Opinion">
                    <articulos>
                        <articulo autor="Juan José Millás">
                            <contenido enlace_inf="http://biblioteca.com/periodico3/articulo1" />
                        </articulo>
                    </articulos>
                </seccion_per>
            </secciones_periodico>
            <indice></indice>
        </periodico>
    </periodicos>
</biblioteca>
